name: Build godot
description: Builds godot with a certain version and certain flags

inputs:
  url:
    description: Godot git url
    default: https://github.com/godotengine/godot
    required: true
  platform:
    description: Platform to build for
    required: true
  flags:
    description: Flags to pass to the build script
    required: false
  target:
    description: Target (release, release_debug, debug)
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup
      uses: bend-n/godot-builds/.github/actions/setup@main
      with:
        ref: ${{ env.ref }}

    - name: Install linux dependencies
      if: inputs.platform == 'x11'
      run: |
        echo ::group::Dependencies
        sudo apt-get update -q
        sudo apt-get install -qqq \
          build-essential pkg-config libx11-dev libxcursor-dev \
          libxinerama-dev libgl1-mesa-dev libglu-dev libasound2-dev \
          libpulse-dev libudev-dev libxi-dev libxrandr-dev yasm \
          libspeechd-dev speech-dispatcher \
          tree
        echo ::endgroup::
      shell: bash

    - name: Setup scons
      run: pip install scons
      shell: bash

    - name: Build Godot
      run: |
        echo ::group::Compilation
        cd godot
        scons_flags=${{ env.flags }}
        cores=$(nproc) || cores=$(sysctl -n hw.ncpu)
        [[ -n "${{ inputs.flags }}" ]] && scons_flags="${{ inputs.flags }}"
        [[ $tools == "yes" ]] && scons_flags="${scons_flags//disable_3d=yes/}" # remove disable_3d=yes if tools=yes
        scons -j$((cores+2)) p=${{ inputs.platform }} tools=${{ env.tools }} target=${{ inputs.target }} use_lto=yes udev=yes $scons_flags
        strip bin/* || true
        ls bin
        echo ::endgroup::
      shell: bash
