name: Build godot
description: Builds godot with a certain version and certain flags

inputs:
  url:
    description: Godot git url
    default: https://github.com/godotengine/godot
    required: true
  platform:
    description: Platform to build for
    required: true
  flags:
    description: Flags to pass to the build script
    required: false

runs:
  using: "composite"
  steps:
    - name: Checkout
      run: |
        [[ -d godot ]] && exit 0 # already checked out
        git clone --depth 1 "${{ inputs.url }}" -b "${{ env.branch }}" godot
        cd godot
        curl 'https://raw.githubusercontent.com/bend-n/godot-2d-builds/main/.github/custom.py' --output custom.py || wget -nv 'https://raw.githubusercontent.com/bend-n/godot-2d-builds/main/.github/custom.py' -O custom.py
      shell: bash

    - name: Install linux dependencies
      if: ${{ inputs.platform }} == "x11"
      run: |
        [[ ${{ inputs.platform }} != "x11" ]] && exit 0
        sudo apt-get update -q
        sudo apt-get install -qqq \
          build-essential pkg-config libx11-dev libxcursor-dev \
          libxinerama-dev libgl1-mesa-dev libglu-dev libasound2-dev \
          libpulse-dev libudev-dev libxi-dev libxrandr-dev yasm tree
      shell: bash

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.9.1"

    - name: Setup SCons
      run: |
        python -c "import sys; print(sys.version)"
        python -m pip install scons
        python --version
        scons --version
      shell: bash

    - name: Build Godot
      run: |
        cd godot
        scons_flags=$flags
        [[ -z "${{ inputs.flags }}" ]] && scons_flags=${{ inputs.flags }}
        scons -j$(($(nproc)+2)) p=${{ inputs.platform }} tools=$tools target=$target use_lto=yes udev=yes $scons_flags
        strip bin/* || true
        ls bin
      shell: bash
