name: "Setup"
description: "Setup the environment for building"

inputs:
  repo:
    description: Godot github owner/repo
    default: godotengine/godot
    required: true
  ref:
    description: Which ref to build
    required: true

runs:
  using: "composite"
  steps:
    - name: Check if clean
      id: clean
      run: |
        if [[ -d godot ]]; then echo "::set-output name=clean::false";
        else echo "::set-output name=clean::true"; fi
      shell: bash

    - uses: actions/checkout@v3
      if: steps.clean.outputs.clean == 'true'
      with:
        repository: ${{ inputs.repo }}
        ref: ${{ inputs.ref }}
        path: "godot"

    - name: Get module data
      if: steps.clean.outputs.clean == 'true'
      run: |
        modules='https://raw.githubusercontent.com/bend-n/godot-2d-builds/main/.github/custom.py'
        curl "$modules" --output godot/custom.py || wget -nv "$modules" -O godot/custom.py
      shell: bash
