name: Build godot on branch 3.x (normal)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
    paths:
      - .github/normal*.py
      - "**.yml"

jobs:
  build:
    name: Build
    uses: bend-n/godot-builds/.github/workflows/reusable-build.yml@main
    with:
      ref: 3.x
      name: godot
      modules-url: https://raw.githubusercontent.com/bend-n/godot-builds/main/.github/normal-build-modules.py
    secrets: inherit
