name: Build godot 2d

on: workflow_dispatch

env:
  branch: 3.x

jobs:
  build-templates:
    runs-on: ubuntu-18.04
    steps:
      - name: Build templates
        uses: bend-n/godot-2d-builds/.github/actions/build-godot@main
        with:
          branch: ${{ env.branch }}
          tools: no
          target: release
          artifact-name: godot-templates
          flags: disable_3d=yes

  build-editor:
    runs-on: ubuntu-18.04
    steps:
      - name: Build editor
        uses: bend-n/godot-2d-builds/.github/actions/build-godot@main
        with:
          branch: ${{ env.branch }}
          tools: yes
          target: release_debug
          artifact-name: godot-editor

  build-headless:
    runs-on: ubuntu-18.04
    steps:
      - name: Build headless
        uses: bend-n/godot-2d-builds/.github/actions/build-godot@main
        with:
          branch: ${{ env.branch }}
          tools: yes
          platform: server
          target: release_debug
          artifact-name: godot-headless
