name: Build godot on branch 3.x (normal)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
    paths:
      - .github/normal*.py
      - .github/workflows/build-3.x-normal.yml
      - Dockerfile

jobs:
  build:
    name: Build
    uses: bend-n/godot-builds/.github/workflows/reusable-build.yml@main
    with:
      ref: 3.x
      name: godot
      build-name: normal
      modules-path: ./.github/normal-build-modules.py
    secrets: inherit
