name: Build godot 2d

on: workflow_dispatch

jobs:
  build-templates:
    runs-on: ubuntu-18.04
    steps:
      - name: Build templates
        uses: bend-n/godot-2d-builds/.github/actions/build-godot@main
        with:
          branch: 3.x
          tools: no
          platform: x11
          target: release
          artifact-name: godot-templates

  build-editor:
    runs-on: ubuntu-18.04
    steps:
      - name: Build editor
        uses: bend-n/godot-2d-builds/.github/actions/build-godot@main
        with:
          branch: 3.x
          tools: yes
          platform: x11
          target: release_debug
          artifact-name: godot-editor

  build-headless:
    runs-on: ubuntu-18.04
    steps:
      - name: Build headless
        uses: bend-n/godot-2d-builds/.github/actions/build-godot@main
        with:
          branch: 3.x
          tools: yes
          platform: server
          target: release_debug
          artifact-name: godot-headless
