name: Build godot on branch 3.x (2d)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
    paths:
      - .github/2d*.py
      - "**.yml"

jobs:
  build:
    name: Build
    uses: bend-n/godot-builds/.github/workflows/reusable-build.yml@main
    with:
      ref: 3.x
    secrets: inherit
