name: Build godot 2d on branch 3.x

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
    paths:
      - .github/*.py
      - "**.yml"

jobs:
  build-3x:
    name: Build 3.x (2d)
    uses: bend-n/godot-2d-builds/.github/workflows/reusable-build.yml@main
    with:
      ref: 3.x
    secrets: inherit
  build-3x-normal:
    name: Build 3.x (normal)
    uses: bend-n/godot-2d-builds/.github/workflows/reusable-build.yml@main
    with:
      ref: 3.x
      name: godot
      modules-url: https://raw.githubusercontent.com/bend-n/godot-2d-builds/main/.github/normal-build-modules.py
    secrets: inherit
