name: Build godot 2d headless and editor for linux

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  branch: 3.x
  tools: yes

jobs:
  build:
    strategy:
      matrix:
        target: [release, release_debug]

    name: Build editor
    runs-on: ubuntu-18.04
    steps:
      - name: Build editor
        uses: bend-n/godot-2d-builds/.github/actions/build-godot@main
        with:
          platform: x11
          target: ${{ matrix.target }}

      - name: Upload artifact
        uses: bend-n/godot-2d-builds/.github/actions/upload-artifact@main
        with:
          name: linux-editor-${{ matrix.target }}
