name: Build godot 2d headless and editor for linux

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        platform: [server, x11]

    name: Build
    runs-on: ubuntu-18.04
    steps:
      - name: Build editor
        uses: bend-n/godot-2d-builds/.github/actions/build-godot@main
        with:
          platform: ${{ matrix.platform }}
          target: release_debug
        env:
          branch: 3.x
          tools: yes

      - name: Upload artifact
        uses: bend-n/godot-2d-builds/.github/actions/upload-artifact@main
        with:
          name: ${{ matrix.platform }}-tools-release
