name: Manually build godot normal

on:
  workflow_dispatch:
    inputs:
      ref:
        type: string
        description: which ref to build
        required: true
      release:
        type: string
        default: "yes"
        description: to make a release
  # turn on when the godot5 is in dev
  # schedule:
  #   - cron: '30 20 * * *'

jobs:
  all-dimensions:
    name: Build ${{ inputs.ref }}
    uses: bend-n/godot-builds/.github/workflows/reusable-build.yml@main
    with:
      ref: ${{ inputs.ref }}
      name: godot
      build-name: bendn
      modules-path: ./.github/normal-build-modules.py
      flags: ""
      make-release: ${{ inputs.release }}
    secrets: inherit
