name: Manually build godot 2d

on:
  workflow_dispatch:
    inputs:
      ref:
        type: string
        description: which ref to build
        required: true

jobs:
  manual-build:
    name: Build ${{ inputs.ref }}
    uses: bend-n/godot-2d-builds/.github/workflows/reusable-build.yml@main
    with:
      ref: ${{ inputs.ref }}
    secrets: inherit
