name: Manually build godot

on:
  workflow_dispatch:
    inputs:
      ref:
        type: string
        description: which ref to build
        required: true

jobs:
  two-dimensions:
    name: Build ${{ inputs.ref }} (2d)
    uses: bend-n/godot-builds/.github/workflows/reusable-build.yml@main
    with:
      ref: ${{ inputs.ref }}
    secrets: inherit
  all-dimensions:
    name: Build ${{ inputs.ref }} (normal)
    uses: bend-n/godot-builds/.github/workflows/reusable-build.yml@main
    with:
      ref: ${{ inputs.ref }}
      name: godot
      build-name: normal
      modules-path: ./.github/normal-build-modules.py
      flags: ""
    secrets: inherit
